[project]
name = "simple-mcp-elicitation-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.12.1",
]

[project.scripts]
simple-mcp-elicitation-server = "server:main"

[tool.uv]
package = true
